export { default as Footer } from './Footer';
export { default as Navbar } from './Navbar';
export { default as Services } from './Services';
export { default as About } from './About';
export { default as Team } from './Team';
export { default as Sponsors } from './Sponsors';
export { default as Contact } from './Contact';
export { default as Landing } from './Landing';
export { default as Portfolio } from './Portfolio';
